language: csharp
solution: ./ElmCommunicator/ElmCommunicator.sln
install:
  - nuget restore ./ElmCommunicator/ElmCommunicator.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./ElmCommunicator/ElmCommunicator.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ElmCommunicator/ElmCommunicatorTests/bin/Release/ElmCommunicatorTests.dll